### ISSUE TITLE
Add support for PCIe device passthrough

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/libvirt#16]
libvirt should be able to pass through PCIe devices from host to guest,

https://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/libvirt_application_development_guide_using_python-Guest_Domains-Device_Config-PCI_Pass.html

**Comment by bryteise** [comment]
Initial support is in, requires manual management for the vfio device on the host side though.
