### ISSUE TITLE
Reliable thread management through Guest life cycle events

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/libvirt#30]
Based on https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2003, newer focal images respawn vcpu threads after a VMExit. Unfortunately libvirt doesn't know of this spawning and still presents the pids of the older threads.

We should enable a notification mechanism from CLH that tell libvirt to refresh all thread information.

**Comment by praveen-pk** [comment]
Vmexit:Reset is triggered by an enhancement in Focal (20.04) images of Ubuntu. This enhancement allowed Focal cloud images to boot just with kernel first. If the boot fails, the second boot is attempted with kernel+initrd. With push back from users, this enhancement is now reverted. Groovy (20.10) has this enhancement reverted. The relevant revert is yet to land in Focal. Progress on this can be tracked at https://bugs.launchpad.net/ubuntu/+source/linux-azure/+bug/1870189.

VmExit is still triggered when reboot is invoked from within a VM. Based on offline discussion, libvirt needs to implement inotify hook/monitor that informs libvirt to refresh its thread information.

**Comment by praveen-pk** [comment]
As the above issue is specific to Ubuntu, Updating the title and repurposing this bug. This Bug will track reliable thread management by libvirt through Guest Lifecycle events. 
We need a mechanism to notify libvirt to refresh thread information if threads are respawned by events like guest reboot, guest reset etc. This bug is going to track this work.

**Comment by praveen-pk** [comment]
inotify based trigger is the recommended approach for this bug.

**Comment by vineethrp** [comment]
Inotify mechanism will not work as it does not work on pseudo filesystems. We have proceeded with parsing procfs for now:
https://github.com/cloud-hypervisor/libvirt/pull/40

**Comment by rbradford** [comment]
You could try using a BPF function and kernel probe to trigger when threads get created/destroyed.

**Comment by vineethrp** [comment]
The main issue with bpf, netlinks etc is that, it might be hard to upstream it to libvirt. I like the idea of HTTP callback API. This would be very similar to qemu monitor interface.

Created an issue to track the callback API: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2273

**Comment by bryteise** [comment]
Fixed via a combination of #40, #45 and #51.
