### ISSUE TITLE
Persist metadata for cloud hypervisor VMs

### ISSUE THREAD

**Issue by bryteise** [cloud-hypervisor/libvirt#33]
@praveen-pk Could you help me flush out the requirements for this feature. I haven't used this for QEMU before.

**Comment by praveen-pk** [comment]
Restarting libvirt daemon should preserve Guest VMs while using CLH.

**Comment by bryteise** [comment]
The current implementation should account for the device management supported by cloud-hypervisor.
What should be done is verify that libvirt restarts will account for hardware devices associated with the VM. We also want to verify if the cgroup, numa, thread pinning works as expected across libvirt restarts.

**Comment by russell-islam** [comment]
> The current implementation should account for the device management supported by cloud-hypervisor.
> What should be done is verify that libvirt restarts will account for hardware devices associated with the VM. We also want to verify if the cgroup, numa, thread pinning works as expected across libvirt restarts.

@bryteise Do we have the issues created for the TODOs ?

**Comment by bryteise** [comment]
@russell-islam Not currently, do you want a specific issue for each item?

**Comment by russell-islam** [comment]
What ever is convenient is fine with me.
