### ISSUE TITLE
PCI Passthrough + SR-IOV Support

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/libvirt#34]
I am tracking this item to enable full support for PCI Passthrough. Follow for https://github.com/cloud-hypervisor/libvirt/pull/25.

In order for VFIO Passthrough to work, a VFIO binding should be created before it can be passed to guest. The above mentioned pull request handles passing PCI device after the VFIO bindings are created on the host.

This issue tracks enabling support in libvirt to automatically create the required bindings without any manual steps.

**Comment by devimc** [comment]
assign this to me please

**Comment by liuw** [comment]
See https://github.com/cloud-hypervisor/libvirt/pull/41

**Comment by devimc** [comment]
thanks @liuw - can we close it?  

cc @praveen-pk

**Comment by praveen-pk** [comment]
On my Test Host I have the following:

```
$ lspci | grep -i nvme
04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
```

I used the following XML to passthrough a PCI device to guest:

```
$ cat ch_pci_pass.xml
<domain type='ch'>
  <name>ch_pci_pass</name>
  <title>Test Cloud Hypervisor</title>
  <description>CPU, PCI</description>
  <os>
    <type>hvm</type>
    <kernel>/home/praween/libvirt/vm/hypervisor-fw</kernel>
  </os>
  <memory unit='G'>4</memory>
  <devices>
    <disk type='file'>
       <source file='/home/praween/libvirt/vm/focal-server-cloudimg-amd64-custom.raw'/>
      <target dev='hda'/>
    </disk>
   <hostdev mode='subsystem' type='pci' managed='no'>
    <source>
      <address domain='0x0000'
               bus='0x04'
               slot='0x00'
               function='0x0'/>
    </source>
  </hostdev>
  </devices>
  <vcpu>4</vcpu>
</domain>
```

When I try to start the VM I see the following error:
```
$ virsh_ch create ch_pci_pass.xml
error: Failed to create domain from ch_pci_pass.xml
error: Requested operation is not valid: Unmanaged PCI device 0000:04:00.0 must be manually detached from the host
```
I had to unbind the PCI device and create a VFIO device with the following commands:

```
echo 0000:04:00.0 > /sys/bus/pci/devices/0000:04:00.0/driver/unbind
echo 144d a808 > /sys/bus/pci/drivers/vfio-pci/new_id
```

Only after running the above commands to unbind and binding the PCI device to VFIO does PCI pass through work for me.

In order for PCI passthrough to work seamlessly, my expectation is for libvirt to handle the binding and unbinding steps. Let me know if I misunderstood this.

**Comment by praveen-pk** [comment]
For SR-IOV, I do not have any hardware to test it. If SR-IOV passthrough to guest was also tested, could you added details on what was tested?

**Comment by liuw** [comment]
You specifically ask libvirt to not manage this device `<hostdev mode='subsystem' type='pci' managed='no'>`.

Try changing `managed` to `yes` and see if that makes a difference for you.

**Comment by devimc** [comment]
@praveen-pk thanks, after taking a look to the code, I see we are using the `vir*` API to prepare the PCI devices, in this case `virHostdevPreparePCIDevicesImpl`, so this is a limitation of libvirt, see 

https://github.com/cloud-hypervisor/libvirt/blob/a132ba9035fa4e383f4a6a4894ff32d632a3237d/src/hypervisor/virhostdev.c#L796-L814

can you try using the qemu driver?

**Comment by liuw** [comment]
> @praveen-pk thanks, after taking a look to the code, I see we are using the `vir*` API to prepare the PCI devices, in this case `virHostdevPreparePCIDevicesImpl`, so this is a limitation of libvirt, see
> 
> https://github.com/cloud-hypervisor/libvirt/blob/a132ba9035fa4e383f4a6a4894ff32d632a3237d/src/hypervisor/virhostdev.c#L796-L814
> 
> can you try using the qemu driver?

This whole `if ... else ...` is enclosed in a bigger `if ... else ...`  for dealing with managed and unmanaged devices. Changing to QEMU won't help. The key is to ask libvirt to manage the device for you, i.e. `managed=yes` in the XML file.

Libvirt is just doing what it is told to do.

**Comment by praveen-pk** [comment]
I confirmed by setting ```managed=yes```, pci passthrough works seamlessly. Thanks @liuw  for the pointer. I confirmed this works both with cloud-hypervisor and qemu.

**Comment by praveen-pk** [comment]
@devimc Checking back on SR-IOV support? Do you have any hardware to SR-IOV based passthrough? did you get a chance to test it?

If SR-IOV is also tested, we can close this issue.

**Comment by devimc** [comment]
@praveen-pk yes, it's working,  I tested SR-IOV passthrough using a `Ethernet Connection X722 for 10GBASE-T`
