### ISSUE TITLE
libvirtd should track liveness of cloud-hypervisor

### ISSUE THREAD

**Issue by vineethrp** [cloud-hypervisor/libvirt#47]
https://github.com/cloud-hypervisor/libvirt/pull/45

The above PR enables libvirtd to track the liveness of cloud-hypervisor if it terminates normally. But in case of abnormal death of cloud-hypervisor(SIGKILL, core, abort etc), libvirtd do not have any clue about this.

libvirtd should track this and mark the VM state accordingly

**Comment by bryteise** [comment]
Hrm not sure what fixed this but if I kill cloud-hypervisor outside of virsh and then run `virsh list --all` I see the ch vm correctly tracked as shut off so closing.

**Comment by bryteise** [comment]
Ah I wasn't killing with `-9` when I do that I see this bug, should be fixed with #78
