### ISSUE TITLE
Error out on unsupported disk types

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/libvirt#56]
CH doesn't support anything other than virtio disks. Attempts to use anything else should error out.

e.g.
```
                <disk type='file'>
                        <source file='/home/rob/workloads/focal.raw'/>
                        <target dev='hda' bus="ide"/>
                </disk>
                <disk type='file'>
                        <source file='/tmp/ubuntu-cloudinit.img'/>
                        <target dev='hdb' bus="ide"/>
                </disk>

```
Should generate an error. If the `bus="ide"` is omitted libvirted maps the hda/hdb to ide and you can see it in the `dumpxml` output.

The correct XML for using CH is:

```
                <disk type='file'>
                        <source file='/home/rob/workloads/focal.raw'/>
                        <target dev='vda' bus="virtio"/>
                </disk>
                <disk type='file'>
                        <source file='/tmp/ubuntu-cloudinit.img'/>
                        <target dev='vdb' bus="virtio"/>
                </disk>
```

**Comment by bryteise** [comment]
So we are currently we only look at the `source` tag's `file` attribute and the `read-only` tag. Nothing else is used. The `target` tag's `dev` attribute is something that is useful in other commands for identifying the device (though we don't support those commands currently), it is only really just a hint. The bus I can check against for virtio only at least. By the way, does the `id` arg of the `--disk` option try to map to vd[a-z] ordering?
