### ISSUE TITLE
Enable bridge mode networking

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/libvirt#87]

**Comment by russell-islam** [comment]
@bryteise @praveen-pk is this task assigned to someone? This task has a higher priority.

**Comment by bryteise** [comment]
@russell-islam we had been paused on enabling new features while we get the cloud-hypervisor code upstreamed.

@praveen-pk could we plan out the submission of the features that we've enabled so far to upstream so we can do the rest of our enablement on upstream directly?

**Comment by praveen-pk** [comment]
@bryteise let us plan the next steps for upstreaming. I was planning to allocate sometime next month for this work. That said, considering the timelines we are aiming for, freezing features will not be possible. 

@russell-islam let us chat offline about the priority for this item. For next month, my plan is to work on https://github.com/cloud-hypervisor/libvirt/issues/90 first and then this item.

**Comment by praveen-pk** [comment]
https://github.com/cloud-hypervisor/libvirt/pull/93 fixes this issue. This can be resolved now.
